spring:
  config:
    activate:
      on-profile: auth

jwt:
  secret-key: ${TOKEN_SECRET}
  access-token:
    expiry: ${ACCESS_TOKEN_EXPIRY}
  refresh-token:
    expiry: ${REFRESH_TOKEN_EXPIRY}

jwk:
  private-key-path: ${JWK_PRIVATE_KEY_PATH}
  public-key-path: ${JWK_PUBLIC_KEY_PATH}