spring:
  application:
    name: bank
  config:
    import:
      - classpath:application-auth.yml
      - classpath:application-db.yml
      - classpath:application-open-api.yml
      - classpath:application-bank.yml
  profiles:
    active: ${PROFILE}

backend:
  endpoint: ${BACKEND_ENDPOINT}