services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: core-bank-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT:-2181}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME:-2000}
    ports:
      - "${ZOOKEEPER_CLIENT_PORT:-2181}:2181"
    networks:
      - core-bank-internal

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: core-bank-kafka
    networks:
      - kafka-net
      - core-bank-internal
    ports:
      - "${KAFKA_PORT_1:-9092}:${KAFKA_PORT_1:-9092}"
      - "${KAFKA_PORT_2:-29092}:${KAFKA_PORT_2:-29092}"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID:-1}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT:-zookeeper:2181}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-1}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:-1}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:-1}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS:-0}
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0.41 # debezium 의 cdc 지원 여부 때문에 버전 8.0.x 사용
    container_name: core-bank-mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT:-23306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - core-bank-internal

  flyway:
    image: flyway/flyway:10
    container_name: core-bank-flyway
    volumes:
      - ./bank/src/main/resources/db/migration:/flyway/sql:ro
    environment:
      FLYWAY_URL: ${DATABASE_URL}
      FLYWAY_USER: ${DATABASE_USERNAME}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
    command:
      - -locations=filesystem:/flyway/sql
      - migrate
    depends_on:
      mysql:
        condition: service_healthy
    restart: "no"
    networks:
      - core-bank-internal

  core-bank-server:
    container_name: core-bank-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${CORE_BANK_PORT:-28080}:8080"
    volumes:
      - ./keys:/app/keys:ro
    depends_on:
      mysql:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    networks:
      - kafka-net
      - core-bank-internal

volumes:
  mysql-data:

networks:
  core-bank-internal:
    driver: bridge
  kafka-net:
    external: true
